### ISSUE TITLE
run jar issue

### ISSUE THREAD

**Issue by ghost** [kepocnhh/StanInitiativeJavaFX#1]
Hello my friend.
I did all the instructions u said for building and running the jar, at the final step when I build the jar, a file named StanInitiative.jar is created and when I do: java -jar StanInitiative.jar this message is shown:
couldn't find or load the main class stan.initiative.Main
NOTE: I do the steps in a directory where the src directory is there. all the steps are successful and I have the bin file with the proper StanTheme.bss and icons in ico folder.(javaw -jar [JAR Name] shows me nothing) --> windows 7 64bit
what is the problem?
thank u.

**Comment by kepocnhh** [comment]
Hi. I not recommended use this repository. It is so old and i  am not support this. If you interested, you can write me on kepocnhh@gmail.com and/or use more late version this project https://github.com/StanleyProjects/Cudgel (branch "dev")
